"""
Django settings for carpool project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""
# settings/base.py

from .base import *
import dj_database_url

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['comercializadora.herokuapp.com']

CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')

AWS_S3_FILE_OVERWRITE = False

MEDIA_BUCKET_NAME = 'cmcmexico'

MEDIA_URL = "https://%s.s3.amazonaws.com/" % MEDIA_BUCKET_NAME

DEFAULT_FILE_STORAGE = 'core.custom_storages.MediaS3BotoStorage'

MEDIA_ROOT = MEDIA_PATH

# Database settings

DATABASES['default'] = dj_database_url.config()

# Algolia settings

ALGOLIA = {
    'APPLICATION_ID': os.environ.get('APPLICATION_ID'),
    'API_KEY': os.environ.get('API_KEY'),
    'SEARCH_KEY': os.environ.get('SEARCH_KEY'),
    'INDEX_PREFIX': 'staging',
}
