# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-16 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('localidad', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('direccion_calle', models.CharField(blank=True, max_length=255)),
                ('direccion_colonia', models.CharField(blank=True, max_length=255)),
                ('direccion_delegacion', models.CharField(blank=True, max_length=255)),
                ('direccion_cp', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(choices=[('distribuidor_bajo', 'Distribuidor Bajo'), ('distribuidor_medio', 'Distribuidor Medio'), ('distribuidor_alto', 'Distribuidor Alto')], default='', max_length=255)),
                ('verificado', models.BooleanField(default=False)),
                ('direccion_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.Estado')),
                ('direccion_pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.Pais')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Distribuidores',
            },
        ),
    ]
