# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-08 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribuidor',
            options={'verbose_name_plural': 'Distribuidores'},
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='tipo',
            field=models.CharField(choices=[('distribuidor_bajo', 'Distribuidor Bajo'), ('distribuidor_medio', 'Distribuidor Medio'), ('distribuidor_alto', 'Distribuidor Alto')], default='', max_length=255),
        ),
    ]
