# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-10 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidor', '0002_auto_20170207_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribuidor',
            name='direccion_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='cities_light.Region'),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='direccion_pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='cities_light.Country'),
        ),
    ]
