# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-06 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170206_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='nombre_producto', max_length=255, null=True),
        ),
    ]
